### PR TITLE
CMake fixes

### PR DESCRIPTION
**Pull request by SoapGentoo**
Hey @mdadams 
I've polished up the CMake files a bit:
1. I've put in the `GNUInstallDirs` module, which is the closest to the GNU FHS conventions in CMake (https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html). This module furthermore defines `CMAKE_INSTALL_LIBDIR`, which we do not need to write out explicitly anymore. Distributions can now change the directories, which requires less hacking on our side and makes for a smoother experience in all distributions, yet files are organised as they were back in the Autotools days when no option is overridden.
2. Dependency checking now only happens if the dependency is requested. This makes everything a bit simpler and less automagicy. In Gentoo (and pretty much all other distros), we only want to build with a dependency when we request it, and if its not there, we fail instead of trying to carry on (https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies). This provides for less implicit behaviour and hard-to-debug build time behaviour.

### CODE REVIEW

**Comment by mdadams** [comment]
@SoapGentoo I have merged by hand all of your changes, except the ones that prevent automagic dependencies.  For automagic dependencies issue, I have taken a different approach.  For the beginner user running cmake to install JasPer, it is highly desirable not to have them need to figure out which libraries are available.  So, I really would like  to have the ability to do automagic dependencies in some cases.  In the case of packagers for Linux distributions, more control is clearly needed, as you have noted.  So, I have attempted to address both sets of users by adding a JAS_ENABLE_AUTOMATIC_DEPENDENCIES option to JasPer.  The idea is that Linux packagers (such as yourself) would set this option to false, with the default being set to true to accommodate beginner users.  Is such a solution acceptable to you?  Incidentally, I also find the automagic dependencies extremely useful for a lot of my testing, where different machines have various combinations of libraries installed and the JasPer code needs to build successfully without customizing the build process for each machine.

The above changes can be picked up in the tagged release version-2.0.5.

**Comment by SoapGentoo** [comment]
@mdadams while I would've preferred a non-automagic approach obviously, I think this is a good middle ground. I've tested your changes and integrated them into Gentoo (https://github.com/gentoo/gentoo/commit/d0457e74a422267e30b94f1e74e709d6349f58e5), and the changes made handling on our side much easier, thanks :smile:!

**Comment by mdadams** [comment]
@SoapGentoo and @jridky With regard to the issue of the name of the library directory (e.g., lib64 versus lib versus something else), should the pkgconfig file for JasPer also be changed?  In particular, it seems that the following file is wrong:
    https://github.com/mdadams/jasper/blob/version-2.0.5/build/jasper.pc.in
Should the line that reads
   libdir=@CMAKE_INSTALL_PREFIX@/lib
be changed to
    libdir=@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@
It would seem that hardcoding "lib" in the package file is wrong.  But I am not sure about this.

**Comment by SoapGentoo** [comment]
@mdadams obviously you're right, I overlooked the pkg-config file, would be nice if you could fix that too.

**Comment by mdadams** [comment]
@SoapGentoo It is fixed now (both the lib and include directories).  See commit 8820f0020884ec56f1f751837b6d46be1968b056.

@SoapGentoo and @jridky  Incidentally, I suspect that the RPM template file is broken, but I don't know enough about such files to fix it.  For that matter, I don't know if anyone uses it.  Maybe I should just drop it?  What do you think?
The file is this one:
    https://github.com/mdadams/jasper/blob/version-2.0.5/build/jasper.spec.in

**Comment by mdadams** [comment]
@SoapGentoo and @jridky Okay, I will drop the spec file then.  Am I correct in my understanding that I should keep the pkgconfig file, however? That is, packagers for Linux distributions will use the upstream pkgconfig file, right?  I presume that this is why you wanted it fixed.  By the way, I am sorry that I am not more familiar with the work that packagers do and the packaging process in general.

**Comment by SoapGentoo** [comment]
@mdadams yes `.pc` files are sacred, never under any circumstances get rid of them. Healthy, correct and minimal `.pc` files are essential to the working of **all** distributions.

**Comment by mdadams** [comment]
@SoapGentoo and @jridky  The spec file is removed now in commit 95a3cae1a3906b69ea3ee4205a0fa6b914a26f66.

@SoapGentoo Thank you for the clarification about the pkgconfig file.  I'll be sure to keep it.

**Pull request closed without merging**
